/**
 * 所有鼠标光标的名称枚举
 */
export enum CursorNameEnum {
  None = "none",
  Default = "default",
  Pointer = "pointer",
  Crosshair = "crosshair",
  Move = "move",
  Grab = "grab",
  Grabbing = "grabbing",
  Text = "text",
  NotAllowed = "not-allowed",
  EResize = "e-resize",
  NResize = "n-resize",
  NeResize = "ne-resize",
  NwResize = "nw-resize",
  SResize = "s-resize",
  SeResize = "se-resize",
  SwResize = "sw-resize",
  WResize = "w-resize",
  NsResize = "ns-resize",
  NeswResize = "nesw-resize",
  NwseResize = "nwse-resize",
  ColResize = "col-resize",
  RowResize = "row-resize",
  AllScroll = "all-scroll",
  ZoomIn = "zoom-in",
  ZoomOut = "zoom-out",
  GrabHand = "grab-hand",
  NotAllowedHand = "not-allowed-hand",
  Pen = "pen",
  Eraser = "eraser",
  Handwriting = "handwriting",
  ZoomInHand = "zoom-in-hand",
  ZoomOutHand = "zoom-out-hand",
}
