import {
  AlignJustify,
  AlignStartVertical,
  AppWindow,
  AppWindowMac,
  ArrowDownNarrowWide,
  ArrowRight,
  ArrowRightFromLine,
  ArrowUpDown,
  Blend,
  Bug,
  Calculator,
  CaseSensitive,
  ChevronUp,
  Circle,
  CircleDot,
  Clipboard,
  Contrast,
  Crosshair,
  Database,
  Delete,
  Eye,
  File,
  FileImage,
  FileStack,
  Folder,
  Fullscreen,
  Gauge,
  Grab,
  Grip,
  Hand,
  HandMetal,
  HardDrive,
  HardDriveDownload,
  Hourglass,
  ImageMinus,
  ImageUpscale,
  Keyboard,
  Languages,
  Layers,
  Lightbulb,
  LineSquiggle,
  ListCheck,
  ListCollapse,
  ListEnd,
  ListMusic,
  ListRestart,
  ListTree,
  LoaderPinwheel,
  MessageSquareText,
  Minus,
  Moon,
  Mouse,
  MouseLeft,
  MouseOff,
  MousePointerClick,
  MouseRight,
  Move,
  Move3d,
  MoveHorizontal,
  MoveVertical,
  Palette,
  PanelRightOpen,
  Pause,
  Pentagon,
  Percent,
  PictureInPicture2,
  Presentation,
  Ratio,
  RefreshCcw,
  RefreshCcwDot,
  RotateCw,
  Scaling,
  ScanEye,
  ScanText,
  Shapes,
  ShieldCheck,
  Skull,
  Slash,
  Space,
  Spline,
  SplinePointer,
  Square,
  SquareArrowDownRight,
  SquareArrowUpLeft,
  SquareDashed,
  SquareM,
  SquarePen,
  Sun,
  SunMoon,
  Tag,
  Tally4,
  TextCursorInput,
  Timer,
  TrendingUpDown,
  Turtle,
  Undo,
  Ungroup,
  Unlink,
  VenetianMask,
  WholeWord,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

export const settingsIcons = {
  hideCursorInPenMode: MouseOff,
  penPressureCurve: Spline,
  autoNamerTemplate: Tag,
  autoNamerSectionTemplate: Tag,
  autoNamerDetailsTemplate: Tag,
  autoNamerTreeNodeTemplate: Tag,
  autoSaveWhenClose: HardDriveDownload,
  autoSave: HardDrive,
  autoSaveInterval: Hourglass,
  autoBackup: Database,
  autoBackupInterval: Hourglass,
  autoBackupLimitCount: FileStack,
  autoBackupCustomPath: Folder,
  autoBackupCustomPath2: Folder,
  autoBackupStrategy: ListTree,
  mouseRightDragBackground: MouseRight,
  mouseLeftMode: MouseLeft,
  doubleClickEmptySpaceAction: MousePointerClick,
  enableDragAutoAlign: AlignStartVertical,
  reverseTreeMoveMode: Move,
  uiScalePercent: Scaling,
  mouseWheelMode: LoaderPinwheel,
  mouseWheelModeReverse: ArrowUpDown,
  mouseWheelWithShiftMode: LoaderPinwheel,
  mouseWheelWithShiftModeReverse: ArrowUpDown,
  mouseWheelWithCtrlMode: LoaderPinwheel,
  mouseWheelWithCtrlModeReverse: ArrowUpDown,
  mouseWheelWithAltMode: LoaderPinwheel,
  mouseWheelWithAltModeReverse: ArrowUpDown,
  hideArrowWhenPointingToConnectPoint: CircleDot,
  doubleClickMiddleMouseButton: Circle,
  doubleClickMiddleMouseButtonOnEntity: Circle,
  mouseSideWheelMode: Grab,
  macMouseWheelIsSmoothed: Mouse,
  enableWindowsTouchPad: Hand,
  macTrackpadAndMouseWheelDifference: Hand,
  macTrackpadScaleSensitivity: HandMetal,
  macEnableControlToCut: ChevronUp,
  allowGlobalHotKeys: Keyboard,
  enableSpaceKeyMouseLeftDrag: Space,
  cameraFollowsSelectedNodeOnArrowKeys: Crosshair,
  moveAmplitude: Move,
  moveFriction: Move,
  scaleExponent: ScanEye,
  cameraZoomInLimitBehavior: ZoomIn,
  cameraZoomOutLimitBehavior: ZoomOut,
  cameraResetViewPaddingRate: Fullscreen,
  cameraResetMaxScale: Fullscreen,
  scaleCameraByMouseLocation: ScanEye,
  cameraKeyboardScaleRate: ScanEye,
  rectangleSelectWhenRight: SquareArrowDownRight,
  rectangleSelectWhenLeft: SquareArrowUpLeft,
  textNodeStartEditMode: ListRestart,
  textNodeContentLineBreak: ListEnd,
  textNodeExitEditMode: ListCheck,
  textNodeExitEditModeOnWheel: LoaderPinwheel,
  textNodeSelectAllWhenStartEditByMouseClick: TextCursorInput,
  textNodeSelectAllWhenStartEditByKeyboard: TextCursorInput,
  textNodeBackspaceDeleteWhenEmpty: Delete,
  textNodeBigContentThresholdWhenPaste: ArrowDownNarrowWide,
  textNodePasteSizeAdjustMode: Scaling,
  textNodeManualDefaultCharWidth: Scaling,
  allowAddCycleEdge: RotateCw,
  enableDragNodeShakeDetachFromEdge: Unlink,
  enableDragEdgeRotateStructure: SplinePointer,
  enableCtrlWheelRotateStructure: RefreshCcw,
  autoLayoutWhenTreeGenerate: ListTree,
  autoLayoutWhenSectionCollapseToggle: ListTree,
  enableTreeGenerateConnectByProbe: ArrowRightFromLine,
  treeGenerateInheritParentColor: Palette,
  enableTabGenerateNodeInInput: Keyboard,
  enableBackslashGenerateNodeInInput: Keyboard,
  gamepadDeadzone: Skull,
  historySize: Undo,
  clipboardPasteMode: Clipboard,
  resizePastedImages: ImageMinus,
  compressImageToWebp: Palette,
  webpQuality: Percent,
  compressImageToBlackAndWhite: Contrast,
  blackAndWhiteThreshold: Gauge,
  wrapImageInGroup: SquareDashed,
  maxPastedImageSize: ImageUpscale,
  autoRefreshStageByMouseAction: RefreshCcwDot,
  isPauseRenderWhenManipulateOvertime: Hourglass,
  pauseRenderWhenTabUnfocused: Pause,
  renderOverTimeWhenNoManipulateTime: Hourglass,
  ignoreTextNodeTextRenderLessThanFontSize: ScanText,
  textIntegerLocationAndSizeRender: WholeWord,
  antialiasing: Calculator,
  defaultFontFamily: CaseSensitive,
  compatibilityMode: Turtle,
  isEnableEntityCollision: Ungroup,
  language: Languages,
  showTipsOnUI: AppWindow,
  useNativeTitleBar: AppWindowMac,
  isClassroomMode: Presentation,
  viewerMode: Eye,
  showQuickSettingsToolbar: PanelRightOpen,
  showRecentFilesThumbnails: FileImage,
  windowBackgroundAlpha: PictureInPicture2,
  windowBackgroundOpacityAfterOpenClickThrough: PictureInPicture2,
  windowBackgroundOpacityAfterCloseClickThrough: PictureInPicture2,
  isRenderCenterPointer: Crosshair,
  centerCrosshairColor: Palette,
  centerCrosshairShape: Shapes,
  centerCrosshairAlpha: Blend,
  showBackgroundHorizontalLines: AlignJustify,
  showBackgroundVerticalLines: Tally4,
  showBackgroundDots: Grip,
  showBackgroundCartesian: Move3d,
  enableTagTextNodesBigDisplay: Tag,
  showTextNodeBorder: Square,
  newNodeScaleByCamera: Scaling,
  newNodeScaleByCameraOffset: Scaling,
  showTreeDirectionHint: TrendingUpDown,
  lineStyle: Spline,
  sectionBitTitleRenderType: SquareM,
  sectionBigTitleThresholdRatio: Ratio,
  sectionBigTitleCameraScaleThreshold: ScanEye,
  sectionBigTitleOpacity: Blend,
  hideSectionContentsWhenBigTitleActive: Layers,
  sectionBackgroundFillMode: Layers,
  sectionInitBorderStyle: SquareDashed,
  autoEnterSectionEditMode: SquarePen,
  nodeDetailsPanel: AppWindow,
  alwaysShowDetails: ListCollapse,
  entityDetailsFontSize: CaseSensitive,
  entityDetailsLinesLimit: ArrowDownNarrowWide,
  entityDetailsWidthLimit: Space,
  showDebug: Bug,
  protectingPrivacy: VenetianMask,
  protectingPrivacyMode: VenetianMask,
  windowCollapsingWidth: MoveHorizontal,
  windowCollapsingHeight: MoveVertical,
  autoAdjustLineEndpointsByMouseTrack: LineSquiggle,
  enableRightClickConnect: MousePointerClick,
  rightClickConnectEdgeType: Spline,
  defaultEdgeLineType: Slash,
  defaultEdgeArrowType: ArrowRight,
  isStealthModeEnabled: Crosshair,
  stealthModeScopeRadius: ScanEye,
  stealthModeReverseMask: CircleDot,
  clearHistoryWhenManualSave: Undo,
  historyManagerMode: Undo,
  soundPitchVariationRange: ListMusic,
  textNodeAutoFormatTreeWhenInput: ListTree,
  treeGenerateCameraBehavior: Fullscreen,
  autoImportTxtFileWhenOpenPrg: File,
  imageImportOrder: ArrowDownNarrowWide,
  stealthModeMaskShape: Pentagon,
  themeMode: SunMoon,
  lightTheme: Sun,
  darkTheme: Moon,
  arrowKeySelectOnlyInViewport: ScanEye,
  enableAutoEdgeWidth: Minus,
  showKeyBindHint: Lightbulb,
  showEditModeHint: MessageSquareText,
  textNodeEditModeOutlineOpacity: SquareDashed,
  colorPanelMouseEnterPreview: Mouse,
  enableOCR: ScanText,
  maxFps: Timer,
  maxFpsUnfocused: Timer,
  aiContextWindow: Gauge,
  aiAutoApproveMcpTools: ShieldCheck,
};
